### ISSUE TITLE
AUTHENTICATION_FAILED Android API 31 

### ISSUE THREAD

**Issue by JoacimWall** [TobiasBuchholz/Plugin.Firebase#161]
Hi and thanks for great nuget. 
 
I run a Maui App that all works on Android Api 33 but on API 31 I get this 
java.util.concurrent.ExecutionException: java.io.IOException: AUTHENTICATION_FAILED
when I access FirebaseCloudMessagingImplementation.GetTokenAsync()

//Joacim

Exception:
 at Plugin.Firebase.CloudMessaging.FirebaseCloudMessagingImplementation.GetTokenAsync()
   at LiberoClub.App.OnSleep() in /Users/joacimwall/GitRepos/nbcMAui/LiberoClub/App.xaml.cs:line 231
  --- End of managed Java.IO.IOException stack trace ---
java.io.IOException: java.util.concurrent.ExecutionException: java.io.IOException: AUTHENTICATION_FAILED
	at com.google.firebase.messaging.FirebaseMessaging.blockingGetToken(FirebaseMessaging.java:625)
	at com.google.firebase.messaging.FirebaseMessaging.lambda$getToken$4$com-google-firebase-messaging-FirebaseMessaging(FirebaseMessaging.java:392)
	at com.google.firebase.messaging.FirebaseMessaging$$ExternalSyntheticLambda9.run(Unknown Source:4)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at com.google.android.gms.common.util.concurrent.zza.run(com.google.android.gms:play-services-basement@@18.1.0:2)
	at java.lang.Thread.run(Thread.java:920)
Caused by: java.util.concurrent.ExecutionException: java.io.IOException: AUTHENTICATION_FAILED
	at com.google.android.gms.tasks.Tasks.zza(com.google.android.gms:play-services-tasks@@18.0.2:5)
	at com.google.android.gms.tasks.Tasks.await(com.google.android.gms:play-services-tasks@@18.0.2:8)
	at com.google.firebase.messaging.FirebaseMessaging.blockingGetToken(FirebaseMessaging.java:623)
	... 9 more
Caused by: java.io.IOException: AUTHENTICATION_FAILED
	at com.google.firebase.messaging.GmsRpc.handleResponse(GmsRpc.java:309)
	at com.google.firebase.messaging.GmsRpc.lambda$extractResponseWhenComplete$0$com-google-firebase-messaging-GmsRpc(GmsRpc.java:320)
	at com.google.firebase.messaging.GmsRpc$$ExternalSyntheticLambda0.then(Unknown Source:2)
	at com.google.android.gms.tasks.zzc.run(com.google.android.gms:play-services-tasks@@18.0.2:3)
	at androidx.window.layout.WindowInfoTrackerImpl$windowLayoutInfo$1$$ExternalSyntheticLambda1.execute(Unknown Source:0)
	at com.google.android.gms.tasks.zzd.zzd(com.google.android.gms:play-services-tasks@@18.0.2:1)
	at com.google.android.gms.tasks.zzr.zzb(com.google.android.gms:play-services-tasks@@18.0.2:5)
	at com.google.android.gms.tasks.zzw.zzb(com.google.android.gms:play-services-tasks@@18.0.2:3)
	at com.google.android.gms.tasks.zzc.run(com.google.android.gms:play-services-tasks@@18.0.2:8)
	at com.google.android.gms.cloudmessaging.zzz.execute(Unknown Source:0)
	at com.google.android.gms.tasks.zzd.zzd(com.google.android.gms:play-services-tasks@@18.0.2:1)
	at com.google.android.gms.tasks.zzr.zzb(com.google.android.gms:play-services-tasks@@18.0.2:5)
	at com.google.android.gms.tasks.zzw.zzb(com.google.android.gms:play-services-tasks@@18.0.2:3)
	at com.google.android.gms.tasks.TaskCompletionSource.setResult(com.google.android.gms:play-services-tasks@@18.0.2:1)
	at com.google.android.gms.cloudmessaging.zzp.zzd(com.google.android.gms:play-services-cloud-messaging@@17.0.0:3)
	at com.google.android.gms.cloudmessaging.zzr.zza(com.google.android.gms:play-services-cloud-messaging@@17.0.0:2)
	at com.google.android.gms.cloudmessaging.zzf.handleMessage(com.google.android.gms:play-services-cloud-messaging@@17.0.0:14)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by TobiasBuchholz** [comment]
Is this issue maybe related to https://github.com/TobiasBuchholz/Plugin.Firebase/issues/162 or could you provide a sample project?

**Comment by TobiasBuchholz** [comment]
Hey @JoacimWall, I'm sorry but I wasn't able to reproduce your issue. For me it worked on Pixel 5, 6 and 7 with the target api levels 30, 31 and 33, see screenshots. Maybe this issue is somehow related to your device?

Google Pixel 5 - API 30
![screenshot-Google Pixel 5-11 0](https://github.com/TobiasBuchholz/Plugin.Firebase/assets/1132836/25c86251-4235-484c-aa5a-ff9338d4364c)

Google Pixel 6 - API 31
![screenshot-Google Pixel 6-12 0](https://github.com/TobiasBuchholz/Plugin.Firebase/assets/1132836/2966b152-12f1-4439-a397-0ed6db0ea3ae)

Google Pixel 7 - API 33
![screenshot-Google Pixel 7-13 0](https://github.com/TobiasBuchholz/Plugin.Firebase/assets/1132836/94547eb2-cb81-4bc0-b0ed-dfb50e201fa5)

**Comment by JoacimWall** [comment]
Hi
Google Play Store generate the error.  
if I add a new pixel 5 device(simulator) API 31 then I get a token.
if I run on a pixel 2 device with google Play Store checked (simulator) API 31 I get error on below row.

if I copy the device and remove Google Play Store then I get the token.

<img width="1494" alt="image" src="https://github.com/TobiasBuchholz/Plugin.Firebase/assets/9278908/a0bba939-16c6-4e38-b25b-1d0625a6f131">
 
<img width="774" alt="image" src="https://github.com/TobiasBuchholz/Plugin.Firebase/assets/9278908/c83b3354-fe2a-498f-834f-2a33a23add39">
<img width="1179" alt="image" src="https://github.com/TobiasBuchholz/Plugin.Firebase/assets/9278908/3bce65aa-a8f2-4111-9d8f-c7d821c0f9f8">
<img width="1177" alt="image" src="https://github.com/TobiasBuchholz/Plugin.Firebase/assets/9278908/39925a82-43c7-4778-a011-a679ae0cb030">
<img width="492" alt="image" src="https://github.com/TobiasBuchholz/Plugin.Firebase/assets/9278908/928b3b30-3d97-4674-8a3d-6cb4d2cf4ed0">

//Joacim
