### ISSUE TITLE
[Installation Issue]: Firebase.Analytics, Privacy Policy not found in .NET 8.0 Maui Project

### ISSUE THREAD

**Issue by archergod** [TobiasBuchholz/Plugin.Firebase#338]
\net6.0-ios16.1\Firebase.Installations.resources\FirebaseInstallations.xcframework\ios-arm64\FirebaseInstallations.framework\FirebaseInstallations_Privacy.bundle\PrivacyInfo.xcprivacy file is not found while installing in my .NET maui Mobile app for Android and ios (only)

**Comment by AdamEssenmacher** [comment]
Steps to reproduce or repro project? Environment details?

**Comment by archergod** [comment]
* On Windows 11 Machine with Visual Studio Community Edition (Version 17.11.2) 
* .NET 8 based Maui Project for iOS and Android only.
* Go to Manage Nuget Packages, search Plugin.Firebase 
* try to add any Plugin.Firebase.Core or Plugin.Firebase.Analytics  or Plugin.Firebase 

Randomly one of file don't get copied 

![image](https://github.com/user-attachments/assets/dc61d486-5091-4e8f-b552-43503144b6bc)

**Comment by archergod** [comment]
Stack trace from Package Manager Output 

```
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\vikas\.nuget\packages\adame.firebase.ios.crashlytics\10.24.0\lib\net6.0-ios16.1\Firebase.Crashlytics.resources\FirebaseCrashlytics.xcframework\ios-arm64\FirebaseCrashlytics.framework\Modules\FirebaseCrashlytics.swiftmodule\arm64-apple-ios.private.swiftinterface'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.IO.File.Create(String path)
   at NuGet.Packaging.StreamExtensions.Testable.MmapCopy(Stream inputStream, String fileFullPath, Int64 size)
   at NuGet.Packaging.StreamExtensions.Testable.CopyToFile(Stream inputStream, String fileFullPath)
   at NuGet.Packaging.PackageFileExtractor.ExtractPackageFile(String source, String target, Stream stream)
   at NuGet.Packaging.PackageArchiveReader.CopyFiles(String destination, IEnumerable`1 packageFiles, ExtractPackageFileDelegate extractFile, ILogger logger, CancellationToken token)
   at NuGet.Packaging.PackageReaderBase.CopyFilesAsync(String destination, IEnumerable`1 packageFiles, ExtractPackageFileDelegate extractFile, ILogger logger, CancellationToken cancellationToken)
   at NuGet.Packaging.PackageExtractor.<>c__DisplayClass5_0.<<InstallFromSourceAsync>b__0>d.MoveNext()
```

**Comment by archergod** [comment]
Okay thanks for information, So we cannot use this plugin when using Visual Studio because I once in past did get it install from Command line as suggested, but it fail during compilation. For some reason I thought it is fixed. 

Time for new editor I guess.
