### ISSUE TITLE
I cannot add the NuGet package because the paths are too long.

### ISSUE THREAD

**Issue by MsShiftDev** [TobiasBuchholz/Plugin.Firebase#341]
Hello,

I am developing a mobile application based on .NET 8.0 and the last missing feature is the support for Push Notifications. I wanted to use this library, but when I click on "Install" in the Visual Studio's NuGet Package Manager, I get the following error trace:

> Restoring packages for C:\Projects\Git\\[APP NAME]\\[APP NAME]\\[APP NAME].csproj...
  GET https://api.nuget.org/v3-flatcontainer/adame.firebase.ios.core/index.json
  GET https://api.nuget.org/v3-flatcontainer/adame.firebase.ios.installations/index.json
  OK https://api.nuget.org/v3-flatcontainer/adame.firebase.ios.installations/index.json 60ms
  OK https://api.nuget.org/v3-flatcontainer/adame.firebase.ios.core/index.json 62ms
  GET https://api.nuget.org/v3-flatcontainer/adame.firebase.ios.installations/10.24.0/adame.firebase.ios.installations.10.24.0.nupkg
  GET https://api.nuget.org/v3-flatcontainer/adame.firebase.ios.core/10.24.0/adame.firebase.ios.core.10.24.0.nupkg
  OK https://api.nuget.org/v3-flatcontainer/adame.firebase.ios.installations/10.24.0/adame.firebase.ios.installations.10.24.0.nupkg 17ms
  OK https://api.nuget.org/v3-flatcontainer/adame.firebase.ios.core/10.24.0/adame.firebase.ios.core.10.24.0.nupkg 33ms
  GET https://api.nuget.org/v3-flatcontainer/adame.firebase.ios.core/10.24.0.1/adame.firebase.ios.core.10.24.0.1.nupkg
  OK https://api.nuget.org/v3-flatcontainer/adame.firebase.ios.core/10.24.0.1/adame.firebase.ios.core.10.24.0.1.nupkg 7ms
  GET https://api.nuget.org/v3-flatcontainer/adame.firebase.ios.dynamiclinks/index.json
  OK https://api.nuget.org/v3-flatcontainer/adame.firebase.ios.dynamiclinks/index.json 41ms
  GET https://api.nuget.org/v3-flatcontainer/adame.firebase.ios.dynamiclinks/10.24.0-alpha1/adame.firebase.ios.dynamiclinks.10.24.0-alpha1.nupkg
  OK https://api.nuget.org/v3-flatcontainer/adame.firebase.ios.dynamiclinks/10.24.0-alpha1/adame.firebase.ios.dynamiclinks.10.24.0-alpha1.nupkg 19ms
  GET https://api.nuget.org/v3-flatcontainer/adame.firebase.ios.remoteconfig/index.json
  OK https://api.nuget.org/v3-flatcontainer/adame.firebase.ios.remoteconfig/index.json 38ms
  GET https://api.nuget.org/v3-flatcontainer/adame.firebase.ios.remoteconfig/10.24.0-alpha1/adame.firebase.ios.remoteconfig.10.24.0-alpha1.nupkg
  OK https://api.nuget.org/v3-flatcontainer/adame.firebase.ios.remoteconfig/10.24.0-alpha1/adame.firebase.ios.remoteconfig.10.24.0-alpha1.nupkg 11ms
  GET https://api.nuget.org/v3-flatcontainer/adame.firebase.ios.abtesting/index.json
  OK https://api.nuget.org/v3-flatcontainer/adame.firebase.ios.abtesting/index.json 37ms
  GET https://api.nuget.org/v3-flatcontainer/adame.firebase.ios.abtesting/10.24.0-alpha1/adame.firebase.ios.abtesting.10.24.0-alpha1.nupkg
  OK https://api.nuget.org/v3-flatcontainer/adame.firebase.ios.abtesting/10.24.0-alpha1/adame.firebase.ios.abtesting.10.24.0-alpha1.nupkg 7ms
System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at NuGet.Packaging.PackageFileExtractor.ExtractPackageFile(String source, String target, Stream stream)
   at NuGet.Packaging.PackageArchiveReader.CopyFiles(String destination, IEnumerable`1 packageFiles, ExtractPackageFileDelegate extractFile, ILogger logger, CancellationToken token)
   at NuGet.Packaging.PackageReaderBase.CopyFilesAsync(String destination, IEnumerable`1 packageFiles, ExtractPackageFileDelegate extractFile, ILogger logger, CancellationToken cancellationToken)
   at NuGet.Packaging.PackageExtractor.<>c__DisplayClass5_0.<<InstallFromSourceAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Common.ConcurrencyUtilities.<ExecuteWithFileLockedAsync>d__5`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.Common.ConcurrencyUtilities.<ExecuteWithFileLockedAsync>d__5`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Packaging.PackageExtractor.<InstallFromSourceAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.ProjectRestoreCommand.<InstallPackageAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.Commands.ProjectRestoreCommand.<>c__DisplayClass15_1.<<InstallPackagesAsync>b__4>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NuGet.Commands.ProjectRestoreCommand.<InstallPackagesAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.ProjectRestoreCommand.<TryRestoreAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.RestoreCommand.<ExecuteRestoreAsync>d__89.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.RestoreCommand.<ExecuteAsync>d__71.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.RestoreRunner.<ExecuteAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.RestoreRunner.<CompleteTaskAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.Commands.RestoreRunner.<RunWithoutCommit>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.DependencyGraphRestoreUtility.<PreviewRestoreProjectsAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<PreviewBuildIntegratedProjectsActionsAsync>d__89.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<PreviewProjectsInstallPackageAsync>d__75.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.VisualStudio.NuGetProjectManagerService.<>c__DisplayClass22_0.<<GetInstallActionsAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.VisualStudio.NuGetProjectManagerService.<CatchAndRethrowExceptionAsync>d__33`1.MoveNext()
Time Elapsed: 00:00:01.2954152
========== Finished ==========

I did investigate this error and I found many people having the exact same or similar issue, but I did not find a solution to solve this. Any tips are very welcomed!

**Comment by AdamEssenmacher** [comment]
Please refer to the documentation in the project readme
