### ISSUE TITLE
CloudFirestore 11.0.0 HardCrash

### ISSUE THREAD

**Issue by barrysohl** [TobiasBuchholz/Plugin.Firebase#388]
Just updated to 11.0.0 of the AdamE libraries, and am now getting a crash on first read of any document with a DataTimeOffset. Here is the exception and top of the stack trace. Known issue? Thanks in advance.

System.TypeLoadException: Could not resolve type with token 01000047 from typeref (expected class 'Firebase.CloudFirestore.Timestamp' in assembly 'Firebase.CloudFirestore, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null')
   at Plugin.Firebase.Firestore.Platforms.iOS.Extensions.NSObjectExtensions.Cast[User](NSDictionary this, String documentId)
   at Plugin.Firebase.Firestore.Platforms.iOS.DocumentSnapshotWrapper`1[[iStatVball3.User, iStatVball3, Version=3.19.0.0, Culture=neutral, PublicKeyToken=null]].get_Data()

**Comment by AdamEssenmacher** [comment]
Plugin.Firebase won't be compatible with Firebase 11 without an update.

**Comment by barrysohl** [comment]
Ok, we will stick with the 10.29.0.3 libraries until Plugin.Firebase is updated. Any guesstimate of when that may be?

**Comment by AdamEssenmacher** [comment]
I was planning on getting to it after publishing native bindings through v.11.6. It looks like earlier versions of 11.x had some known bugs, particularly affecting ObjectiveC, that have been fixed. So I probably wouldn't recommend using 11.0 even if it did work with this plugin.

By the way... The breaking change is simply that the `Timestamp` class was moved from Firebase.CloudFirestore to Firebase.Core. Fixing it really should be as easy as tracking down any build errors to make sure the type is referenced from the correct assembly. You could always speed this along by opening a PR :)

**Comment by barrysohl** [comment]
I unfortunately have no experience with being a contributor, nor building libraries for that matter, otherwise I'd be happy to.

**Comment by AdamEssenmacher** [comment]
It's fine--I should have it done in a few days I think!

**Comment by barrysohl** [comment]
Awesome, thanks! One of these days, I will dive into learning how to contribute to these libraries we rely on so heavily.

**Comment by AdamEssenmacher** [comment]
This should be done with the latest release.

**Comment by barrysohl** [comment]
Awesome, thanks!

-Barry

**Comment by barrysohl** [comment]
We are unable to update to 11.6.0 of AdamE.iOS.Firebase.Auth due to the follow error:

System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.

It seems to be failing on this package:
https://api.nuget.org/v3-flatcontainer/adame.google.ios.googledatatransport/10.1.0/adame.google.ios.googledatatransport.10.1.0.nupkg

Stack trace:
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
at NuGet.Packaging.PackageFileExtractor.ExtractPackageFile(String source, String target, Stream stream)
at NuGet.Packaging.PackageArchiveReader.CopyFiles(String destination, IEnumerable`1 packageFiles, ExtractPackageFileDelegate extractFile, ILogger logger, CancellationToken token)
at NuGet.Packaging.PackageReaderBase.CopyFilesAsync(String destination, IEnumerable`1 packageFiles, ExtractPackageFileDelegate extractFile, ILogger logger, CancellationToken cancellationToken)
at NuGet.Packaging.PackageExtractor.<>c__DisplayClass5_0.<<InstallFromSourceAsync>b__0>d.MoveNext()


Any ideas?

Thanks,
-Barry

**Comment by AdamEssenmacher** [comment]
That's the long-path issue: https://github.com/AdamEssenmacher/GoogleApisForiOSComponents/blob/main/Readme.md#windows--visual-studio-long-path-issue

**Comment by barrysohl** [comment]
Ugh ok. We’ll try the workaround. I miss Visual Studio Mac! We’re only using Visual Studio Windows (via Parallels) because Rider has been unusable for us for MAUI Android development, particularly debugging.

Thanks,
-Barry

**Comment by barrysohl** [comment]
Hello, just wanted to follow-up on my previous desperate cry for help with Plugin.Firebase.CloudFirestore… I was wondering if you happen to have time for another quick contract project? There is a mission critical issues we are having with Plugin.Firebase.CloudFirestore described in #526. The plugin does not seem to deserialize nested Dictionary objects. If we had a new project, we would simply flatten the data structure, or work around it in some other way. But we have hundreds of GBs of data already using this structure, which worked fine in Xamarin. Now we don’t seem to have a way to access that data in MAUI. Any help would be much appreciated!!

Thanks,
-Barry

DemiVision, LLC
