### ISSUE TITLE
The Crashlytics build ID is missing

### ISSUE THREAD

**Issue by OvrBtn** [TobiasBuchholz/Plugin.Firebase#391]
Hello, I've been trying to get the package to work. I just need the push notifications and only for android. 

The steps are a little big vague sometimes but I did the basic setup from https://github.com/TobiasBuchholz/Plugin.Firebase and the android specific stuff from https://github.com/TobiasBuchholz/Plugin.Firebase/blob/development/docs/cloud_messaging.md

I'd be extremely grateful for any help.

When trying to build I get:

Java.Lang.RuntimeException: 'Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.IllegalStateException: The Crashlytics build ID is missing. This occurs when Crashlytics tooling is absent from your app's build configuration. Please review Crashlytics onboarding instructions and ensure you have a valid Crashlytics account.'

Log from Output window:

```
[FirebaseApp] Device unlocked: initializing all Firebase APIs for app [DEFAULT]
[TetheringManager] registerTetheringEventCallback:com.ovrbtn.studencki_usos_put
[FirebaseCrashlytics] Initializing Firebase Crashlytics 18.3.2 for com.ovrbtn.studencki_usos_put
[DynamiteModule] Considering local module com.google.android.gms.measurement.dynamite:92 and remote module com.google.android.gms.measurement.dynamite:13
[DynamiteModule] Selected local version of com.google.android.gms.measurement.dynamite
[FirebaseCrashlytics] .
[FirebaseCrashlytics] .     |  | 
[FirebaseCrashlytics] .     |  |
[FirebaseCrashlytics] .     |  |
[FirebaseCrashlytics] .   \ |  | /
[FirebaseCrashlytics] .    \    /
[FirebaseCrashlytics] .     \  /
[FirebaseCrashlytics] .      \/
[FirebaseCrashlytics] .
[FirebaseCrashlytics] The Crashlytics build ID is missing. This occurs when Crashlytics tooling is absent from your app's build configuration. Please review Crashlytics onboarding instructions and ensure you have a valid Crashlytics account.
[FirebaseCrashlytics] .
[FirebaseCrashlytics] .      /\
[FirebaseCrashlytics] .     /  \
[FirebaseCrashlytics] .    /    \
[FirebaseCrashlytics] .   / |  | \
[FirebaseCrashlytics] .     |  |
[chatty] uid=10168(com.ovrbtn.studencki_usos_put) identical 1 line
[FirebaseCrashlytics] .     |  |
[FirebaseCrashlytics] .
[AndroidRuntime] Shutting down VM
[AndroidRuntime] FATAL EXCEPTION: main
[AndroidRuntime] Process: com.ovrbtn.studencki_usos_put, PID: 12927
[AndroidRuntime] java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.IllegalStateException: The Crashlytics build ID is missing. This occurs when Crashlytics tooling is absent from your app's build configuration. Please review Crashlytics onboarding instructions and ensure you have a valid Crashlytics account.
[AndroidRuntime] 	at android.app.ActivityThread.installProvider(ActivityThread.java:7244)
[AndroidRuntime] 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6780)
[AndroidRuntime] 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6697)
[AndroidRuntime] 	at android.app.ActivityThread.access$1300(ActivityThread.java:237)
[AndroidRuntime] 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
[AndroidRuntime] 	at android.os.Handler.dispatchMessage(Handler.java:106)
[AndroidRuntime] 	at android.os.Looper.loop(Looper.java:223)
[AndroidRuntime] 	at android.app.ActivityThread.main(ActivityThread.java:7656)
[AndroidRuntime] 	at java.lang.reflect.Method.invoke(Native Method)
[AndroidRuntime] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
[AndroidRuntime] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
[AndroidRuntime] Caused by: java.lang.IllegalStateException: The Crashlytics build ID is missing. This occurs when Crashlytics tooling is absent from your app's build configuration. Please review Crashlytics onboarding instructions and ensure you have a valid Crashlytics account.
[AndroidRuntime] 	at com.google.firebase.crashlytics.internal.common.CrashlyticsCore.onPreExecute(CrashlyticsCore.java:136)
[AndroidRuntime] 	at com.google.firebase.crashlytics.FirebaseCrashlytics.init(FirebaseCrashlytics.java:149)
[AndroidRuntime] 	at com.google.firebase.crashlytics.CrashlyticsRegistrar.buildCrashlytics(CrashlyticsRegistrar.java:60)
[AndroidRuntime] 	at com.google.firebase.crashlytics.CrashlyticsRegistrar.$r8$lambda$Pfd5XmDCFzNyAT9o9H6rDnTBQE4(Unknown Source:0)
[AndroidRuntime] 	at com.google.firebase.crashlytics.CrashlyticsRegistrar$$ExternalSyntheticLambda0.create(Unknown Source:2)
[AndroidRuntime] 	at com.google.firebase.tracing.ComponentMonitor.lambda$processRegistrar$0(ComponentMonitor.java:38)
[AndroidRuntime] 	at com.google.firebase.tracing.ComponentMonitor$$ExternalSyntheticLambda0.create(Unknown Source:4)
[AndroidRuntime] 	at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0$com-google-firebase-components-ComponentRuntime(ComponentRuntime.java:160)
[AndroidRuntime] 	at com.google.firebase.components.ComponentRuntime$$ExternalSyntheticLambda1.get(Unknown Source:4)
[AndroidRuntime] 	at com.google.firebase.components.Lazy.get(Lazy.java:53)
[AndroidRuntime] 	at com.google.firebase.components.ComponentRuntime.doInitializeEagerComponents(ComponentRuntime.java:322)
[AndroidRuntime] 	at com.google.firebase.components.ComponentRuntime.initializeEagerComponents(ComponentRuntime.java:312)
[AndroidRuntime] 	at com.google.firebase.FirebaseApp.initializeAllApis(FirebaseApp.java:607)
[AndroidRuntime] 	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:300)
[AndroidRuntime] 	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:264)
[AndroidRuntime] 	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:249)
[AndroidRuntime] 	at com.google.firebase.provider.FirebaseInitProvider.onCreate(FirebaseInitProvider.java:69)
[AndroidRuntime] 	at android.content.ContentProvider.attachInfo(ContentProvider.java:2388)
[AndroidRuntime] 	at android.content.ContentProvider.attachInfo(ContentProvider.java:2358)
[AndroidRuntime] 	at com.google.firebase.provider.FirebaseInitProvider.attachInfo(FirebaseInitProvider.java:61)
[AndroidRuntime] 	at android.app.ActivityThread.installProvider(ActivityThread.java:7239)
[AndroidRuntime] 	... 10 more
[monodroid-assembly] open_from_bundles: failed to load assembly System.Console.dll
Loaded assembly: /data/data/com.ovrbtn.studencki_usos_put/files/.__override__/System.Console.dll [External]
[FA] App measurement initialized, version: 79000
[FA] To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
[FA] To enable faster debug mode event logging run:
[FA]   adb shell setprop debug.firebase.analytics.app com.ovrbtn.studencki_usos_put
[FA] Tag Manager is not found and thus will not be used
**Java.Lang.RuntimeException:** 'Loading...'

[FirebaseInstanceId] Token retrieval failed: SERVICE_NOT_AVAILABLE. Will retry token retrieval
[FirebaseInstanceId] Token retrieval failed: SERVICE_NOT_AVAILABLE. Will retry token retrieval
[FirebaseInstanceId] Token retrieval failed: SERVICE_NOT_AVAILABLE. Will retry token retrieval
[FirebaseInstanceId] Token retrieval failed: SERVICE_NOT_AVAILABLE. Will retry token retrieval
```

**Comment by AdamEssenmacher** [comment]
If you're goal is to just get push notifications, why add crashlytics?
