### ISSUE TITLE
Fails to build on IOS when installed with other Nuget packages (MAUI)

### ISSUE THREAD

**Issue by clough360** [TobiasBuchholz/Plugin.Firebase#81]
### Description
When adding Plugin.firebase to an existing working .NET MAUI project, the app fails to build on IOS (still builds on Android).

The following error is reported:
```
/Users/runner/.nuget/packages/skiasharp.nativeassets.ios/2.88.1-preview.63/buildTransitive/net6.0-ios13.6/SkiaSharp.NativeAssets.iOS.targets(6,9): error MSB4096: 
The item "/Users/runner/Library/Caches/XamarinBuildDownload/GSgnI-5.0.2/Frameworks/GoogleSignIn.framework" in item list "NativeReference" does not define a value for metadata "FrameworkFilename".  
In order to use this metadata, either qualify it by specifying %(NativeReference.FrameworkFilename), or ensure that all items in this list define a value for this metadata. [/Users/runner/work/1/s/src/App.csproj]
```

This error is reported whether building locally or using CI (Azure DevOps).

I have confirmed the issue by removing the plugin nuget package, which allows the project to build.

This seems to be a clash with skiasharp. The other package I have which uses skiasharp is Mapsui

### .NET SDK Versions
Fails on both 6.0.300 and 6.0.400

**Comment by Kapusch** [comment]
Hi @clough360 , indeed your error seems pointing an issue from SkiaSharp library, although it may be already fixed with this [PR](https://github.com/mono/SkiaSharp/pull/2198).

Did you try to update SkiaSharp library upto v2.88.1 ?

**Comment by clough360** [comment]
I'm using the latest version of MAPSUI (4.0.0 b5) which has a dependency on SkiaSharp >=2.88.1:
![image](https://user-images.githubusercontent.com/12503052/194888327-a6c0227b-6cc5-426d-a29d-3c5d9109b01d.png)

I've checked in the build directory and it is definitely using 2.88.1

**Comment by clough360** [comment]
I have manyally added Nuget packages for
* SkiaSharp
* SkiaSharp.Harfbuzz
* SkiaSharp.Views.Maui.Controls
* SkiaSharp.Views.Maui.Core

When I add v2.88.1, the app will not compile. 
When I add v2.88.3 (latest stable), the app will compile.

The critical lib was Harfbuzz, the app would not compile without this at 2.88.3

I will raise a ticket for MAPSUI to update dependencies.

**Comment by OroviaTraining** [comment]
On IOS when I run, The app icon is created OK. But the app terminates with the message

[0:] An error occurred: 'Object reference not set to an instance of an object.'. Callstack: '   at Plugin.Firebase.CloudMessaging.FirebaseCloudMessagingImplementation.RegisterForRemoteNotifications()
   at Plugin.Firebase.CloudMessaging.FirebaseCloudMessagingImplementation.Initialize()
   at Plugin.Firebase.iOS.CrossFirebase.Initialize(UIApplication app, NSDictionary options, CrossFirebaseSettings settings, Options firebaseOptions, String name)
   at MauiFirebaseDemo.MauiProgram.<>c.<RegisterFirebaseServices>b__1_3(UIApplication app, NSDictionary launchOptions) in C:\SourceCode\PlayGround\MauiFirebaseDemo\MauiProgram.cs:line 36
   at Microsoft.Maui.MauiUIApplicationDelegate.<>c__DisplayClass6_0.<FinishedLaunching>b__0(FinishedLaunching del)
   at Microsoft.Maui.LifecycleEvents.LifecycleEventServiceExtensions.InvokeLifecycleEvents[FinishedLaunching](IServiceProvider services, Action`1 action)
   at Microsoft.Maui.MauiUIApplicationDelegate.FinishedLaunching(UIApplication application, NSDictionary launchOptions)
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName)
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
   at MauiFirebaseDemo.Program.Main(String[] args) in C:\SourceCode\PlayGround\MauiFirebaseDemo\Platforms\iOS\Program.cs:line 13
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)'
The app has been terminated.

**Comment by Kapusch** [comment]
Hi @OroviaTraining , this sounds completely different.
Could you please reference your issue in a new ticket ?
